import json, re
ROOT = "/Users/mihaiperdum/Projects/Sentinel Vault/.claude/worktrees/sv-7-personal-data"
calls = json.load(open("calls-final.json"))
man = open(f"{ROOT}/manifest.yml").read().split("  scopes:\n")[1].split("  content:")[0]
kept = re.findall(r"^    - ([a-z:.\-]+)\s*$", man, re.M)
full = open("manifest.full.yml").read().split("  scopes:\n")[1].split("  content:")[0]
before = re.findall(r"^    - ([a-z:.\-]+)\s*$", full, re.M)
removed = [s for s in before if s not in kept]
K = set(kept)
rows, links, dev = [], [], []
for c in calls:
    if not c.get("spec"):
        links.append(c); continue
    alts = c.get("alts") or []
    cov = next((a for a in alts if set(a) <= K), None)
    r = (c["file"], c["line"], c["mode"], c["spec"], " or ".join("+".join(a) for a in alts) or "(none documented)", "+".join(cov) if cov else ("n/a — already refused before 7.0" if not alts or "permission/check" in c["spec"] else "NOT COVERED"))
    (dev if c["devOnly"] else rows).append(r)
bad = [r for r in rows if r[5] == "NOT COVERED"]
out = []
w = out.append
w("# Sentinel Vault 7.0.0 — permission scopes, call by call")
w("")
w("GENERATED by the 7.0.0 scope audit (2026-10-05). Every outgoing Atlassian call in `src/` is listed with the scopes Atlassian accepts for it (the `x-atlassian-oauth2-scopes` of the Confluence v1/v2, JSM and Assets OpenAPI specs, fetched 2026-10-04) and the scope that still covers it after the trim. Where the spec offers alternatives (classic OR granular), either set is enough.")
w("")
w(f"Production 6.11.0 declares 38 scopes. 7.0.0 adds one (`report:personal-data`, the weekly personal-data check) and removes {len(removed)}: {len(kept)} scopes. Calls not covered after the trim: **{len(bad)}**.")
w("")
w(f"## Removed ({len(removed)})")
w("")
why = {
 "read:confluence-space.summary": "No call needs it; no space or label trigger. Content search with expand=space is covered by search:confluence (live: backup discovery still returns spaceKey/spaceName).",
 "read:confluence-props": "Granular-era duplicate: no v1 content-property endpoint is called; every property read/write goes through v2 page/space properties (read/write:page, read/write:space).",
 "read:content:confluence": "No v1 call lists it as an alternative that the classic scopes don't already cover.",
 "write:content:confluence": "Same: classic write:confluence-content stays and covers labels, pageTree delete, restrictions.",
 "write:attachment:confluence": "Granular alternative of the v1 attachment upload/update calls; classic write:confluence-file (+ write:confluence-props for the un-trash PUT) stays and covers them.",
 "read:comment:confluence": "The app only CREATES footer comments (v2 POST /footer-comments needs write:comment:confluence, kept); it never reads comments.",
 "read:content.property:confluence": "No v1 content-property call; v2 properties use read:page / read:space.",
 "write:content.property:confluence": "No v1 content-property call; v2 properties use write:page / write:space.",
 "read:content.restriction:confluence": "The one restriction read (v1 GET /content/{id}/restriction) is covered by read:confluence-content.all.",
 "write:content.restriction:confluence": "The one restriction write (v1 PUT /content/{id}/restriction, backup page) is covered by write:confluence-content.",
 "read:content.metadata:confluence": "Granular alternative of the sync contentbody/convert call; read:confluence-content.all stays (live: convert answers 200 after the trim).",
 "read:content.permission:confluence": "Granular alternative of v1 POST /content/{id}/permission/check; classic read:confluence-content.permission stays.",
}
for s in removed: w(f"- `{s}` — {why.get(s, '')}")
w("")
w("## Proposed for removal on 2026-10-04 but KEPT")
w("")
w("- `read:confluence-content.summary` — REQUIRED by the five product triggers (page created/updated, attachment updated/trashed/deleted): Forge's events reference says page and attachment events \"require the OAuth scope `read:confluence-content.summary`\", and `forge lint` fails with `permission-scope-required` on all five when it is removed (measured 2026-10-05). Removing it would have silently switched off seal enforcement.")
w("- `read:label:confluence` — `forge lint` maps the page-label read (`/wiki/api/v2/pages/{id}/labels`, src/server/infra/labels.js:20-21) to `GET /labels` and fails without it, while the v2 spec lists only read:page:confluence. Ambiguous, so it stays.")
w("")
w("## Live proof on development (wolfaenpak, 2026-10-05)")
w("")
w("Same lanes, same dev install (e0f4fa35), before the trim (39 scopes: production 6.11.0's 38 plus report:personal-data, dev 9.x) and after it (27 scopes, dev 10.x, finally 18.x at 10f1aa7).")
w("")
w("| Lane | Before (39 = production 38 + report:personal-data) | After (27) |")
w("|---|---|---|")
w("| REST specs (22) | 21 passed, 1 flaky (gate-revert) | 20 passed; gate-revert and revert-destructive red in the run right after the upgrade, revert-destructive and sealed-media green on a quiet re-run; gate-revert red |")
w("| Read-confirmation groups | 6/6 | 6/6 |")
w("| Purge witness | 4/4 | 4/4 |")
w("| Privacy erasure (real closed account) | 18/18 | 18/18 |")
w("| Backup relocate / restore / delete / re-create | 13/13 | 13/13 |")
w("| TOTP enrol / signed approval / replay | 12/12 | 12/12 |")
w("| Browser lane (34) | 26 passed, 3 failed (a11y Dialog, classification badge, first-run merge; all three also fail on 6.6.0) | 25 passed, the same 3 failed, plus sealed-delete-restore-journey |")
w("| Endpoint probe (hook) | convert 200, group picker 200, membersByGroupId 200, pageTree delete 202 | identical |")
w("| Backup discovery (content search expand=space, restriction read) | spaceKey WFH, restricted true | identical |")
w("")
w("The reds that were green are event latency, not scopes. gate-revert, revert-destructive and the restore journey wait for Confluence's page-updated / attachment-trashed events, and on dev today those arrived 30 s to 10 min late in bursts (the issue in docs/FORGE-SUPPORT-EVENT-LATENCY-2026-09-15.md). Proof: (1) the [PAGE-EVENT] first-line log shows the handler simply had not been invoked yet when the specs gave up, then the events landed in bursts; (2) an A/B with the FULL 39 scopes redeployed on the same install failed both too: the restore journey on the identical assertion (the trashed event had not landed), gate-revert even earlier, waiting 30 s for the created-page event (zero user update events delivered in that window); (3) a bisect (control, then each group of the 12 removed, then all 12) delivered a user page update within 4-5 s every time. `forge logs` after the trim: no scope refusal; every 401 is AUTH_TYPE_UNAVAILABLE (a user-context call with no user), the same lines as before the trim.")
w("")
w("## Not REST: what else needs a scope")
w("")
w("| Consumer | Needs | Kept |")
w("|---|---|---|")
w("| triggers `avi:confluence:created:page`, `updated:page`, `updated:attachment` | read:confluence-content.summary | yes |")
w("| triggers `avi:confluence:trashed:attachment`, `deleted:attachment` | read:confluence-content.summary **and** write:confluence-content (\"Trashed and deleted events, in addition to the above, require the OAuth scope `write:confluence-content`\" — Forge events reference) | yes, both |")
w("| `privacy.reportPersonalData` (weekly personal-data check) | report:personal-data | yes (added in 7.0.0) |")
w("| `@forge/kvs` (storage and secrets) | storage:app | yes |")
w("| Custom UI `@forge/bridge` | invoke / router / view / Modal / showFlag only — no `requestConfluence` from the browser, so no scope | — |")
w("| `llm` module | no scope | — |")
w("")
w("## Every call")
w("")
w("| File:line | As | Endpoint | Accepted scopes | Covered after 7.0 by |")
w("|---|---|---|---|---|")
for f, l, m, sp, acc, cov in sorted(rows):
    w(f"| {f.replace('src/','')}:{l} | {m} | {sp} | {acc} | {cov} |")
w("")
w("## Dev-only test hook (stripped from production)")
w("")
w("| File:line | Endpoint | Accepted scopes | Covered by |")
w("|---|---|---|---|")
for f, l, m, sp, acc, cov in sorted(dev):
    w(f"| {f.replace('src/','')}:{l} | {sp} | {acc} | {cov} |")
w("")
w("## Path-like literals that are not calls")
w("")
w("Page links built for the UI or for comments (viewpage.action, the app's own pages) and title or id builders: " + ", ".join(sorted({c['file'].replace('src/','') + ':' + str(c['line']) for c in links})) + ".")
w("")
w("## Method")
w("")
w("Every template literal in `src/` that starts with `/wiki/`, `/rest/`, `/jsm/` or a `${base}` path variable, and every double-quoted string literal that starts with `/wiki/`, `/rest/`, `/jsm/` or `/app/`, was extracted with its file:line, enclosing call, `asApp`/`asUser` and HTTP method (routes held in a variable are followed to the `requestConfluence(var, …)` that sends them), then matched to the OpenAPI operation. Manual resolutions: `${base}/properties` (base = v2 page or space), `${collection}/{id}/attachments` (pages or blogposts), the sync `contentbody/convert` (dropped from the current spec; scopes taken from its async sibling and proven live), `/rest/api/group` without `/wiki`, and the v1 space permission check (not in the spec; refused 401 before 7.0 as well, fail-closed). `forge lint` on the trimmed manifest: 0 errors, 0 warnings, 1 approval (the major). The first pass (5dba6ae) read template literals only and missed two string-literal calls, `GET /wiki/api/v2/classification-levels` (classification/logic.js:214, read:configuration:confluence) and `GET /wiki/api/v2/spaces` (classification/actions.js:53, read:space:confluence); both are covered by kept scopes (independent review, 2026-10-05).")
open(f"{ROOT}/docs/SCOPES-7.0.md", "w").write("\n".join(out) + "\n")
print("rows", len(rows), "dev", len(dev), "links", len(links), "NOT COVERED", bad)
print("removed", removed)
