/*
 * GENERATED by scripts/gen-build-info.mjs — do NOT hand-edit.
 * A placeholder is COMMITTED so the Forge backend bundle always resolves this import;
 * the generator overwrites it locally on every npm build / deploy (commit churn expected).
 */
export const BUILD_INFO = { gitSha: "8d069e4", builtAt: "2026-09-14T06:30:48.011Z" };
