/*
 * GENERATED by scripts/gen-build-info.mjs — do NOT hand-edit.
 * A placeholder is COMMITTED so the Forge backend bundle always resolves this import;
 * the generator overwrites it locally on every npm build / deploy (commit churn expected).
 */
export const BUILD_INFO = { gitSha: "115e023", builtAt: "2026-08-14T17:16:00.545Z" };
