/*
 * GENERATED by scripts/gen-build-info.mjs — do NOT hand-edit.
 * A placeholder is COMMITTED so the Forge backend bundle always resolves this import;
 * the generator overwrites it locally on every npm build / deploy (commit churn expected).
 */
export const BUILD_INFO = { gitSha: "b990297", builtAt: "2026-10-02T07:13:00.444Z" };
